name: flutter_filter_dialog
description: Easily convert your usual single/multiple select or dropdown into page, dialog, or bottom sheet with various choice input such as radio, checkbox, switch, chips, or custom widget.
version: 1.2.0
#author: J.Sharifian <spisoftco@gmail.com>
homepage: https://github.com/SPSpisoft/flutter_filter_dialog

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  dio: ^5.3.3
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: